### ISSUE TITLE
Register events during the shutdown phase

### ISSUE THREAD

**Issue by BingZi-233** [TriggerReactor/TriggerReactor#316]
Recently, it was discovered that the plug-in will try to register events when the server is shut down, but it is intercepted by the server. It's unknown for what reason

`
[21:01:10] [Server thread/INFO]: [TriggerReactor] Disabling TriggerReactor v3.0.5
[21:01:10] [Server thread/INFO]: [TriggerReactor] Finalizing the scheduled script executions...
[21:01:10] [Server thread/INFO]: [TriggerReactor] Shut down complete!
[21:01:10] [AreaTriggerManager -- EntityTrackingThread/WARN]: Exception in thread "AreaTriggerManager -- EntityTrackingThread" org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
[21:01:10] [AreaTriggerManager -- EntityTrackingThread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:518)
[21:01:10] [AreaTriggerManager -- EntityTrackingThread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.callSyncMethod(CraftScheduler.java:235)
[21:01:10] [AreaTriggerManager -- EntityTrackingThread/WARN]: 	at io.github.wysohn.triggerreactor.bukkit.manager.trigger.AreaTriggerManager$1.getEntitiesSync(AreaTriggerManager.java:57)
[21:01:10] [AreaTriggerManager -- EntityTrackingThread/WARN]: 	at io.github.wysohn.triggerreactor.bukkit.manager.trigger.AreaTriggerManager$1.run(AreaTriggerManager.java:77)
[21:01:10] [AreaTriggerManager -- EntityTrackingThread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[21:01:10] [Server thread/INFO]: [TrHologram] Disabling TrHologram v1.11
`

**Comment by wysohn** [comment]
This is a known issue, yet it's quite a minor one.

It doesn't affect anything. Will fix it at some time though

**Comment by BingZi-233** [comment]
感谢您的回应！
可以在onDisable函数中检查是否注册了什么。
