### ISSUE TITLE
Incompatibility with Sponge in 3.1.0 beta

### ISSUE THREAD

**Issue by rkdrns4747** [TriggerReactor/TriggerReactor#320]
`
[11:59:20] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'trg c' for source EntityPlayerMP['Gold_Magic'/46, l='world', x=-2493.30, y=75.88, z=-2857.07]: null java.lang.NullPointerException: null at io.github.wysohn.triggerreactor.core.main.TriggerReactorCore.onCommand(TriggerReactorCore.java:538) ~[TriggerReactorCore.class:?] at io.github.wysohn.triggerreactor.sponge.main.TriggerReactor$1.process(TriggerReactor.java:226) ~[TriggerReactor$1.class:?] at org.spongepowered.common.command.SpongeCommandDispatcher.process(SpongeCommandDispatcher.java:355) ~[SpongeCommandDispatcher.class:1.12.2-2838-7.2.3] at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:360) [SpongeCommandManager.class:1.12.2-2838-7.2.3] at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:665) [dh.class:?] at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:960) [pa.class:?] at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:939) [pa.class:?] at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?] at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?] at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:219) [PacketPhaseUtil.class:1.12.2-2838-7.2.3] at net.minecraft.network.PacketThreadUtil$1.redirect$zlb000$impl$redirectToPhaseTracker(SourceFile:540) [hv$1.class:?] at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?] at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_261] at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_261] at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?] at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:308) [SpongeImplHooks.class:1.12.2-2838-7.2.3] at net.minecraft.server.MinecraftServer.redirect$zjf000$onRun(MinecraftServer.java:4682) [MinecraftServer.class:?] at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?] at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?] at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]`
    

Ran in spongeforge 1.12.2 -2838-7.23

**Comment by wysohn** [comment]
@rkdrns4747 
Was the plugin fully loaded?

Seems like something went wrong when the plugin was loading.

**Comment by wysohn** [comment]
![image](https://user-images.githubusercontent.com/8789836/88488750-1bd6a900-cf44-11ea-97dd-f651b07b3b6d.png)

**Comment by rkdrns4747** [comment]
```
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: java.lang.NullPointerException
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at io.github.wysohn.triggerreactor.sponge.main.TriggerReactor.lambda$migrateOldConfig$1(TriggerReactor.java:286)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at io.github.wysohn.triggerreactor.tools.ContinuingTasks.run(ContinuingTasks.java:17)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at io.github.wysohn.triggerreactor.tools.ContinuingTasks$Builder.run(ContinuingTasks.java:33)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at io.github.wysohn.triggerreactor.sponge.main.TriggerReactor.migrateOldConfig(TriggerReactor.java:340)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at io.github.wysohn.triggerreactor.sponge.main.TriggerReactor.onInitialize(TriggerReactor.java:265)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at org.spongepowered.common.event.listener.GameAboutToStartServerEventListener_TriggerReactor_onInitialize19.handle(Unknown Source)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:97)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:458)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:419)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:255)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:361)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at net.minecraftforge.fml.common.LoadController.redirect$zza000$forgeImpl$PostEvent(LoadController.java:568)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at net.minecraftforge.fml.common.Loader.serverAboutToStart(Loader.java:859)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:292)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:268)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at java.lang.Thread.run(Unknown Source)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: java.lang.NullPointerException
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at java.util.Objects.requireNonNull(Unknown Source)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at java.util.Optional.<init>(Unknown Source)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at java.util.Optional.of(Unknown Source)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at io.github.wysohn.triggerreactor.sponge.main.TriggerReactor.lambda$migrateOldConfig$4(TriggerReactor.java:300)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at io.github.wysohn.triggerreactor.tools.ContinuingTasks.run(ContinuingTasks.java:17)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at io.github.wysohn.triggerreactor.tools.ContinuingTasks$Builder.run(ContinuingTasks.java:33)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at io.github.wysohn.triggerreactor.sponge.main.TriggerReactor.migrateOldConfig(TriggerReactor.java:340)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at io.github.wysohn.triggerreactor.sponge.main.TriggerReactor.onInitialize(TriggerReactor.java:265)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at org.spongepowered.common.event.listener.GameAboutToStartServerEventListener_TriggerReactor_onInitialize19.handle(Unknown Source)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:97)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:458)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:419)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:255)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:361)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at net.minecraftforge.fml.common.LoadController.redirect$zza000$forgeImpl$PostEvent(LoadController.java:568)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at net.minecraftforge.fml.common.Loader.serverAboutToStart(Loader.java:859)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:292)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:268)
[17:21:10] [Server thread/INFO] [STDERR]: [io.github.wysohn.triggerreactor.tools.ContinuingTasks:run:19]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
```
sorry for too late. I got from discord.
