### ISSUE TITLE
CommandMap backward compatibility

### ISSUE THREAD

**Issue by wysohn** [TriggerReactor/TriggerReactor#328]
```
[19:56:13 ERROR]: Error occurred while enabling TriggerReactor v3.1.0 (Is it up to date?)
java.lang.NullPointerException: null
	at io.github.wysohn.triggerreactor.bukkit.manager.trigger.CommandTriggerManager.synchronizeCommandMap(CommandTriggerManager.java:124) ~[TriggerReactor-bukkit-latest-3.1.0.jar:?]
	at io.github.wysohn.triggerreactor.core.manager.trigger.command.AbstractCommandTriggerManager.reload(AbstractCommandTriggerManager.java:143) ~[TriggerReactor-bukkit-latest-3.1.0.jar:?]
	at io.github.wysohn.triggerreactor.bukkit.main.AbstractJavaPlugin.onEnable(AbstractJavaPlugin.java:115) ~[TriggerReactor-bukkit-latest-3.1.0.jar:?]
	at io.github.wysohn.triggerreactor.bukkit.main.TriggerReactor.onEnable(TriggerReactor.java:37) ~[TriggerReactor-bukkit-latest-3.1.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:347) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.reload(CraftServer.java:809) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
	at org.bukkit.Bukkit.reload(Bukkit.java:604) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:28) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchServerCommand(CraftServer.java:689) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
	at net.minecraft.server.v1_13_R2.DedicatedServer.handleCommandQueue(DedicatedServer.java:459) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:418) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_261]
```

**Comment by wysohn** [comment]
```
[13:39:47] [Server thread/INFO]: [TriggerReactor] Global variables were loaded from GsonConfigSource{file=plugins\TriggerReactor\var.json}
[13:39:47] [Server thread/WARN]: java.lang.NoSuchMethodException: org.bukkit.craftbukkit.v1_15_R1.CraftServer.syncCommands()
[13:39:47] [Server thread/WARN]:        at java.lang.Class.getMethod(Unknown Source)
[13:39:47] [Server thread/WARN]:        at io.github.wysohn.triggerreactor.bukkit.manager.trigger.CommandTriggerManager.synchronizeCommandMap(CommandTriggerManager.java:111)
[13:39:47] [Server thread/WARN]:        at io.github.wysohn.triggerreactor.core.manager.trigger.command.AbstractCommandTriggerManager.reload(AbstractCommandTriggerManager.java:143)
[13:39:47] [Server thread/WARN]:        at io.github.wysohn.triggerreactor.bukkit.main.AbstractJavaPlugin.onEnable(AbstractJavaPlugin.java:115)
[13:39:47] [Server thread/WARN]:        at io.github.wysohn.triggerreactor.bukkit.main.TriggerReactor.onEnable(TriggerReactor.java:21)
[13:39:47] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[13:39:47] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
[13:39:47] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[13:39:47] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:464)
[13:39:47] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:378)
[13:39:47] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:457)
[13:39:47] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:274)
[13:39:47] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784)
[13:39:47] [Server thread/WARN]:        at java.lang.Thread.run(Unknown Source)
[13:39:47] [Server thread/WARN]: [TriggerReactor] Couldn't find syncCommands(). This may indicate that you are using very very old version of Bukkit. Please report this to TR team, so we can work on it.
```

**Comment by wysohn** [comment]
It works as intended.

We can't fully support outdated version
