### ISSUE TITLE
If a command trigger has the same name as another command trigger's alias, the entire server crashes.

### ISSUE THREAD

**Issue by soshimee** [TriggerReactor/TriggerReactor#336]
### **Before/읽어주세요**

Make sure that you have used `/trg debug` so that the more detailed error message will show up in the console.
신고전에 `/trg debug` 명령어를 사용해서 디버그 모드를 켜주세요. 그래야 콘솔창에 더 자세한 정보가 나옵니다.

---

**Describe the bug/버그 증상**
어떤 증상이 발상하는지 작성 해 주세요.
Title

**Server information/서버 정보**
1. Spigot/Paper/Bukkit/etc... version/사용중인 서버 버전
2. TriggerReactor version/사용중인 트리거 버전
Paper 1.16.4
3.1.0 beta 6

**Error message/에러 메시지**
If error message (in red color) shows up in Minecraft client or on the console, report it here
에러메시지 (빨간색) 가 나타났다면 클라이언트와 콘솔의 메시지를 올려주세요.

**Others/그 밖의 정보들**
그 외의 다른 문제가 있으면 여기에 작성 해 주세요.

**Comment by wysohn** [comment]
Crash log please

**Comment by soshimee** [comment]
java.lang.IllegalArgumentException: Command /xxx cannot be alias for itself
	at org.apache.commons.lang.Validate.isTrue(Validate.java:136)
	at org.bukkit.craftbukkit.v1_16_R3.help.CommandAliasHelpTopic.<init>(CommandAliasHelpTopic.java:18)
	at org.bukkit.craftbukkit.v1_16_R3.help.SimpleHelpMap.initializeCommands(SimpleHelpMap.java:156)
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:429)
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:469)
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239)
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:936)
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178)
	at java.lang.Thread.run(Thread.java:748)

**Comment by wysohn** [comment]
## Confirmed Test Cases

```
/trg cmd tupe #MESSAGE "dupe"
/trg cmd dupe #MESSAGE "tupe"
/trg cmd tupe aliases tupe dupe
/trg cmd dupe aliases tupe dupe
```
< restart server >
```
/trg cmd tupe aliases tupe dupe
/trg cmd dupe aliases tupe dupe
```
---
no server crashes
