### ISSUE TITLE
Repeat Trigger does not work

### ISSUE THREAD

**Issue by RookieAND** [TriggerReactor/TriggerReactor#429]
### **Before/읽어주세요**

Make sure that you have used `/trg debug` so that the more detailed error message will show up in the console.
신고전에 `/trg debug` 명령어를 사용해서 디버그 모드를 켜주세요. 그래야 콘솔창에 더 자세한 정보가 나옵니다.

---

**Describe the bug/버그 증상**

When I ran server. NPE of RepeatTrigger has been occured.

**Server information/서버 정보**
1. Paper 1.16.5 lastest build.
2. TriggerReactor 3.3.0.2 (pre)

**Error message/에러 메시지**

```
[21:50:27 WARN]: java.lang.NullPointerException
[21:50:27 WARN]:        at io.github.wysohn.triggerreactor.core.manager.trigger.repeating.RepeatingTrigger.run(RepeatingTrigger.java:110)
[21:50:27 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[21:50:27 WARN]: [TriggerReactor] Repeating Trigger [TriggerInfo{triggerName=announce, config='{AutoStart=true, Interval=10000}'}] encountered an error!
[21:50:27 WARN]: [TriggerReactor] null
[21:50:27 WARN]: [TriggerReactor] If you are an administrator, see console for more details.
```
full log -> https://pastebin.com/BSrLneE3

**Others/그 밖의 정보들**
RepeatTrigger doesn't work either.

**Comment by wysohn** [comment]
@RookieAND 
Can you possibly test this again with the changes I added? It would be really appreciated.

**Comment by Sayakie** [comment]
I think it has been already resolved. So close this issue ;)
