### ISSUE TITLE
Repeat Trigger does not work

### ISSUE THREAD

**Issue by wysohn** [TriggerReactor/TriggerReactor#441]
```
[00:01:33 WARN]: java.lang.NullPointerException
[00:01:33 WARN]:        at io.github.wysohn.triggerreactor.core.manager.trigger.repeating.RepeatingTrigger.run(RepeatingTrigger.java:110)
[00:01:33 WARN]:        at java.base/java.lang.Thread.run(Thread.java:829)
[00:01:33 WARN]: [TriggerReactor] Repeating Trigger [TriggerInfo{triggerName=reboottime, config='{AutoStart=true, Interval=30000}'}] encountered an error!
[00:01:33 WARN]: [TriggerReactor] null
[00:01:33 WARN]: [TriggerReactor] If you are an administrator, see console for more details.
[00:01:33 WARN]: java.lang.NullPointerException
[00:01:33 WARN]:        at io.github.wysohn.triggerreactor.core.manager.trigger.repeating.RepeatingTrigger.run(RepeatingTrigger.java:126)
[00:01:33 WARN]:        at java.base/java.lang.Thread.run(Thread.java:829)
[00:01:33 WARN]: [TriggerReactor] Repeating Trigger [TriggerInfo{triggerName=reboottime, config='{AutoStart=true, Interval=30000}'}] encountered an error!
[00:01:33 WARN]: [TriggerReactor] null
[00:01:33 WARN]: [TriggerReactor] If you are an administrator, see console for more details.
```

**Comment by wysohn** [comment]
dupe #429
