### ISSUE TITLE
MySQL true시 오류

### ISSUE THREAD

**Issue by fadfhkdfga** [TriggerReactor/TriggerReactor#613]
### **Before/읽어주세요**

Make sure that you have used `/trg debug` so that the more detailed error message will show up in the console.
신고전에 `/trg debug` 명령어를 사용해서 디버그 모드를 켜주세요. 그래야 콘솔창에 더 자세한 정보가 나옵니다.

---

**Describe the bug/버그 증상**
MySQL true로 해서 정상적으로 세팅을 했는데 아래와 같은 오류가 출력됩니다.
혹시 추가적으로 설정해야하는 부분이 있나요?

**Server information/서버 정보**
1. Spigot/Paper/Bukkit/etc... version/사용중인 서버 버전: Paper 1.20.1
2. TriggerReactor version/사용중인 트리거 버전: latest-3.4.1

**Error message/에러 메시지**
[23:46:50 ERROR]: Error occurred while enabling TriggerReactor v3.4.1-Release (Is it up to date?)
java.lang.NoClassDefFoundError: com/mysql/jdbc/jdbc2/optional/MysqlConnectionPoolDataSource
        at io.github.wysohn.triggerreactor.bukkit.main.AbstractJavaPlugin$MysqlSupport.<init>(AbstractJavaPlugin.java:345) ~[TriggerReactor-bukkit-latest-3.4.1-Release.jar:?]
        at io.github.wysohn.triggerreactor.bukkit.main.AbstractJavaPlugin.initMysql(AbstractJavaPlugin.java:251) ~[TriggerReactor-bukkit-latest-3.4.1-Release.jar:?]
        at io.github.wysohn.triggerreactor.bukkit.main.AbstractJavaPlugin.onEnable(AbstractJavaPlugin.java:214) ~[TriggerReactor-bukkit-latest-3.4.1-Release.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-196]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.mysql.jdbc.jdbc2.optional.MysqlConnectionPoolDataSource
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 15 more

**Comment by Cupelt** [comment]
Jshader 적용 하셨나요?

**Comment by fadfhkdfga** [comment]
> Jshader 적용 하셨나요?

네 1.1 사용중입니다.
