### ISSUE TITLE
Unexpected exception while parsing console command when unknown command typing

### ISSUE THREAD

**Issue by LimuLhw** [TriggerReactor/TriggerReactor#648]
**Describe the bug/버그 증상**
잘못된 명령어를 입력 할 시 예외 발생 메시지 출력

**Server information/서버 정보**

1. Paper 1.20.6, 윈도우 10 64비트 환경
2. TriggerReactor 3.4.7 버전

**Error message/에러 메시지**
If error message (in red color) shows up in Minecraft client or on the console, report it here
에러메시지 (빨간색) 가 나타났다면 클라이언트와 콘솔의 메시지를 올려주세요.

바닐라 마인크래프트의 명령어를 잘못 입력할 때:
```
[12:43:35 WARN]: Unexpected exception while parsing console command "give"
org.bukkit.command.CommandException: Unhandled exception executing 'give' in org.bukkit.craftbukkit.command.VanillaCommandWrapper(give)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:174) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:964) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at org.bukkit.craftbukkit.CraftServer.dispatchServerCommand(CraftServer.java:949) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:521) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:468) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1571) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.util.NoSuchElementException: No value present
        at java.base/java.util.Optional.orElseThrow(Optional.java:377) ~[?:?]
        at io.papermc.paper.command.brigadier.MessageComponentSerializer.message(MessageComponentSerializer.java:22) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-124-0fcf3e3]
        at io.papermc.paper.brigadier.PaperBrigadier.componentFromMessage(PaperBrigadier.java:45) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-124-0fcf3e3]
        at net.minecraft.commands.Commands.finishParsing(Commands.java:396) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at net.minecraft.commands.Commands.performCommand(Commands.java:351) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at net.minecraft.commands.Commands.performCommand(Commands.java:342) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at net.minecraft.commands.Commands.performPrefixedCommand(Commands.java:332) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at org.bukkit.craftbukkit.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:55) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:164) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        ... 8 more
```

그 이외 잘못된 명령어/존재하지 않는 명령어를 입력 할 때:
```
[12:46:27 WARN]: Unexpected exception while parsing console command "aaaaa"
java.lang.NullPointerException: command
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:921) ~[guava-32.1.2-jre.jar:?]
        at com.destroystokyo.paper.exception.ServerCommandException.<init>(ServerCommandException.java:28) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:989) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:968) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at org.bukkit.craftbukkit.CraftServer.dispatchServerCommand(CraftServer.java:949) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:521) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:468) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1571) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Others/그 밖의 정보들**
그 외의 다른 문제가 있으면 여기에 작성 해 주세요.

TRG 플러그인을 뺀 상태에서는 발생하지 않습니다.
![image](https://github.com/TriggerReactor/TriggerReactor/assets/6559842/ded794cc-8f00-4244-989a-d26acb6d4b6a)

**Comment by LimuLhw** [comment]
인게임 플레이어가 알 수 없는 명령어 작성 시:
```
[08:45:12 INFO]: Limu_lhw issued server command: /aaaa
[08:45:12 ERROR]: Error executing task on Server
java.util.NoSuchElementException: No value present
        at java.base/java.util.Optional.orElseThrow(Optional.java:377) ~[?:?]
        at io.papermc.paper.command.brigadier.MessageComponentSerializer.message(MessageComponentSerializer.java:22) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-134-4f13be9]
        at io.papermc.paper.brigadier.PaperBrigadier.componentFromMessage(PaperBrigadier.java:45) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-134-4f13be9]
        at net.minecraft.commands.Commands.finishParsing(Commands.java:396) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at net.minecraft.commands.Commands.performCommand(Commands.java:351) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at net.minecraft.commands.Commands.performCommand(Commands.java:342) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at net.minecraft.commands.Commands.performCommand(Commands.java:337) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2202) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2176) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1511) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1488) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1411) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1377) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1238) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-134-4f13be9]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```
이 오류 역시 현 TRG 3.4.7에서 발생합니다.

**Comment by LimuLhw** [comment]
Spigot 환경에서는 해당 문제가 발생하지 않습니다.
(Spigot 1.21 기준)
