### ISSUE TITLE
In Game Editor Cannot define variables for most strings

### ISSUE THREAD

**Issue by chickiyeah** [TriggerReactor/TriggerReactor#653]
### **Before/읽어주세요**

Make sure that you have used `/trg debug` so that the more detailed error message will show up in the console.
신고전에 `/trg debug` 명령어를 사용해서 디버그 모드를 켜주세요. 그래야 콘솔창에 더 자세한 정보가 나옵니다.

---

**Describe the bug/버그 증상**
어떤 증상이 발상하는지 작성 해 주세요.
This is an incomprehensible bug symptom.

de = event.getEntity().getType() X
q = event.getEntity().getType() O

**Server information/서버 정보**
1. Paper version 1.21.3-27-master@661839e (2024-11-11T19:22:47Z) (Implementing API version 1.21.3-R0.1-SNAPSHOT)
2. TriggerReactor version/사용중인 트리거 버전 : 3.4.7 Releasee
**Error message/에러 메시지**
If error message (in red color) shows up in Minecraft client or on the console, report it here
에러메시지 (빨간색) 가 나타났다면 클라이언트와 콘솔의 메시지를 올려주세요.

`[03:50:06] [Server thread/INFO]: Debugging is set to true
[03:50:06] [Server thread/INFO]: [io.github.wysohn.triggerreactor.core.main.TRGCommandHandler] Debugging state: true
[03:54:07] [User Authenticator #3/INFO]: UUID of player chicki_yeah is fe0be918-5271-4994-a856-76f0f9d8c9dc
[03:54:08] [Server thread/INFO]: chicki_yeah joined the game
[03:54:08] [Server thread/INFO]: chicki_yeah[/49.170.122.104:60798] logged in with entity id 946080 at ([world]-273.3239415621969, 95.0269325185376, -183.29223356115682)
[03:54:53] [Server thread/INFO]: chicki_yeah issued server command: /trg custom org.bukkit.event.entity.EntityDeathEvent entitydeath
[03:55:13] [Async Chat Thread - #22/WARN]: java.lang.NumberFormatException: For input string: "="
[03:55:13] [Async Chat Thread - #22/WARN]: 	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
[03:55:13] [Async Chat Thread - #22/WARN]: 	at java.base/java.lang.Integer.parseInt(Integer.java:662)
[03:55:13] [Async Chat Thread - #22/WARN]: 	at java.base/java.lang.Integer.parseInt(Integer.java:778)
[03:55:13] [Async Chat Thread - #22/WARN]: 	at TriggerReactor-bukkit-latest-3.4.7-Release.jar//io.github.wysohn.triggerreactor.core.manager.ScriptEditManager.onChat(ScriptEditManager.java:144)
[03:55:13] [Async Chat Thread - #22/WARN]: 	at TriggerReactor-bukkit-latest-3.4.7-Release.jar//io.github.wysohn.triggerreactor.bukkit.manager.ScriptEditListener.onChat(ScriptEditListener.java:42)
[03:55:13] [Async Chat Thread - #22/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor47.execute(Unknown Source)
[03:55:13] [Async Chat Thread - #22/WARN]: 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[03:55:13] [Async Chat Thread - #22/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[03:55:13] [Async Chat Thread - #22/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[03:55:13] [Async Chat Thread - #22/WARN]: 	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[03:55:13] [Async Chat Thread - #22/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[03:55:13] [Async Chat Thread - #22/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[03:55:13] [Async Chat Thread - #22/WARN]: 	at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:378)
[03:55:13] [Async Chat Thread - #22/WARN]: 	at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:85)
[03:55:13] [Async Chat Thread - #22/WARN]: 	at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2437)
[03:55:13] [Async Chat Thread - #22/WARN]: 	at net.minecraft.server.network.ServerGamePacketListenerImpl.broadcastChatMessage(ServerGamePacketListenerImpl.java:2553)
[03:55:13] [Async Chat Thread - #22/WARN]: 	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$9(ServerGamePacketListenerImpl.java:2201)
[03:55:13] [Async Chat Thread - #22/WARN]: 	at net.minecraft.util.FutureChain.lambda$append$1(FutureChain.java:25)
[03:55:13] [Async Chat Thread - #22/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
[03:55:13] [Async Chat Thread - #22/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[03:55:13] [Async Chat Thread - #22/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[03:55:13] [Async Chat Thread - #22/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[03:55:13] [Async Chat Thread - #22/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[03:55:13] [Server thread/INFO]: Could not execute this trigger.
[03:55:13] [Server thread/INFO]:  >> Caused by: java.lang.NumberFormatException
[03:55:13] [Server thread/INFO]: For input string: "="
[03:55:13] [Server thread/INFO]: If you are administrator, see console for details.
`

**Others/그 밖의 정보들**
그 외의 다른 문제가 있으면 여기에 작성 해 주세요.

**Comment by chickiyeah** [comment]
https://github.com/TriggerReactor/TriggerReactor/pull/654
